name = "Bottomless Pit of People"
version = "1.09.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37af6be7ffc4c179e69b099154783d0276c2b931add5fdfeb27a5a4780d91584"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
